Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 1
  print_batch_step: 10
  save_model_dir: ./output/rec/r45_abinet/
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: /content/PaddleOCR/vi_vocab.txt
  character_type: en
  max_text_length: 100
  infer_mode: false
  use_space_char: true
  save_res_path: ./output/rec/predicts_abinet.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.99
  clip_norm: 20.0
  lr:
    name: Piecewise
    decay_epochs:
    - 6
    values:
    - 0.0001
    - 1.0e-05
  regularizer:
    name: L2
    factor: 0.0
Architecture:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform: null
  Backbone:
    name: ResNet45
  Head:
    name: ABINetHead
    use_lang: true
    iter_size: 3
Loss:
  name: CELoss
  smoothing: false
  ignore_index: 100
PostProcess:
  name: ABINetLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/PaddleOCR
    label_file_list: ["/content/PaddleOCR/gen_data_230504/train_test_txt/230504_mix_train.txt"]
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - ABINetRecAug: null
    - ABINetLabelEncode: null
    - ABINetRecResizeImg:
        image_shape:
        - 3
        - 32
        - 512
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 8
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/PaddleOCR
    label_file_list: ["/content/PaddleOCR/gen_data_230504/train_test_txt/230504_mix_train.txt"]
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - ABINetLabelEncode: null
    - ABINetRecResizeImg:
        image_shape:
        - 3
        - 32
        - 512
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4
    use_shared_memory: false
profiler_options: null
